/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 02:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _04_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입</title>\r\n");
      out.write("<link href=\"./css/join.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/join.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <form name=\"frm\" id=\"frm\" action=\"JoinServlet\">\r\n");
      out.write(" <h1>회원 가입</h1>\r\n");
      out.write("  <label for=\"name\">이름</label><span> * </span>\r\n");
      out.write("  <input type=\"text\" name=\"name\" value=\"김정보\" required><br>\r\n");
      out.write("  <label>주민등록번호  </label><span style=\"color:red;\"> * </span>\r\n");
      out.write("   <input type=\"text\" name=\"jumin_1\" value=\"890719\" required> - \r\n");
      out.write("   <input type=\"text\" name=\"jumin_2\" value=\"2012123\" required> <br>\r\n");
      out.write("   \r\n");
      out.write("   <label for=\"id\"> 아이디  </label><span style=\"color:red;\"> * </span>\r\n");
      out.write("   <input type=\"text\" id=\"id\" name=\"id\" value=\"pinksung\" required><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"pwd\"> 비밀번호 </label><span style=\"color:red;\"> * </span> \r\n");
      out.write("    <input type=\"password\" id=\"pwd\" name=\"pwd\" value=\"1234\" required><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"pwd_re\"> 비밀번호 확인  </label><span style=\"color:red;\"> * </span>\r\n");
      out.write("    <input type=\"password\" id=\"pwd_re\" name=\"pwd_re\" value=\"1234\" required><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\">이메일 </label> &nbsp;\r\n");
      out.write("    <input type=\"text\" name=\"email\" value=\"pinksung\"> @ \r\n");
      out.write("    <input type=\"text\" name=\"email_dns\" value=\"\">\r\n");
      out.write("    <select name=\"emailaddr\">\r\n");
      out.write("        <option value=\"\">직접입력</option>\r\n");
      out.write("        <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("        <option value=\"empal.com\">empal.com</option>\r\n");
      out.write("        <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("        <option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("        <option value=\"msn.com\">msn.com</option>\r\n");
      out.write("        <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("        <option value=\"nate.com\" selected=\"selected\">nate.com</option>                \r\n");
      out.write("    </select><br>    \r\n");
      out.write("    \r\n");
      out.write("    <label for=\"zip\">우편번호</label> &nbsp;\r\n");
      out.write("    <input type=\"text\" id=\"zip\" name=\"zip\" value=\"321-212\"><br>\r\n");
      out.write("           \r\n");
      out.write("    <label for=\"addr1\">주소</label> &nbsp;\r\n");
      out.write("    <input type=\"text\" id=\"addr1\" name=\"addr1\"  value=\"서울시 송파구 잠실2동\">\r\n");
      out.write("    <input type=\"text\" name=\"addr2\" value=\"엘스 아파트 201동 1203호\"><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"phone\">핸드폰번호</label>  &nbsp;\r\n");
      out.write("    <input type=\"tel\" id=\"phone\" name=\"phone\" value=\"010-2321-2312\"><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"job\">직업</label>  &nbsp;\r\n");
      out.write("    <select id=\"job\" name=\"job\" size=\"3\">  \r\n");
      out.write("       <option value=\"학생\">학생</option> \r\n");
      out.write("       <option value=\"컴퓨터/인터넷\">컴퓨터/인터넷</option> \r\n");
      out.write("       <option value=\"언론\">언론</option> \r\n");
      out.write("       <option value=\"공무원\" selected=\"selected\">공무원</option> \r\n");
      out.write("       <option value=\"군인\">군인</option> \r\n");
      out.write("       <option value=\"서비스업\">서비스업</option> \r\n");
      out.write("       <option value=\"교육\">교육</option> \r\n");
      out.write("    </select><br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"chk_mail\">메일/SMS 정보 수신</label>  &nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"chk_mail\" name=\"chk_mail\" checked> 수신 \r\n");
      out.write("    <input type=\"radio\" id=\"chk_mail\" name=\"chk_mail\"> 수신거부<br>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"interest\">관심분야</label>  &nbsp;\r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"생두\"> 생두         \r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"원두\" checked> 원두         \r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"로스팅\"> 로스팅         \r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"핸드드립\" checked> 핸드드립         \r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"에스프레소\" checked> 에스프레소         \r\n");
      out.write("      <input type=\"checkbox\" id=\"interest\" name=\"interest\" value=\"창업\"> 창업<br><br>\r\n");
      out.write("    \r\n");
      out.write(" <div id=\"button\">\r\n");
      out.write("    <input type=\"submit\" value=\"회원가입\" onclick=\"return check()\">\r\n");
      out.write("    <input type=\"reset\" value=\"취소\">\r\n");
      out.write(" </div>\r\n");
      out.write("</form> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
